/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TempisticheRouteImport } from './routes/tempistiche'
import { Route as SavingsRouteImport } from './routes/savings'
import { Route as RinnovoScadenzeRouteImport } from './routes/rinnovo-scadenze'
import { Route as PostFreezeRouteImport } from './routes/post-freeze'
import { Route as NuoviFabbisogniRouteImport } from './routes/nuovi-fabbisogni'
import { Route as MonitoraggioRouteImport } from './routes/monitoraggio'
import { Route as MasterplanSupcRouteImport } from './routes/masterplan-supc'
import { Route as MasterplanRuRouteImport } from './routes/masterplan-ru'
import { Route as MasterplanConsolidatoRouteImport } from './routes/masterplan-consolidato'
import { Route as ContrattiAttiviRouteImport } from './routes/contratti-attivi'
import { Route as CapacityRouteImport } from './routes/capacity'
import { Route as AttivitaRouteImport } from './routes/attivita'
import { Route as IndexRouteImport } from './routes/index'

const TempisticheRoute = TempisticheRouteImport.update({
  id: '/tempistiche',
  path: '/tempistiche',
  getParentRoute: () => rootRouteImport,
} as any)
const SavingsRoute = SavingsRouteImport.update({
  id: '/savings',
  path: '/savings',
  getParentRoute: () => rootRouteImport,
} as any)
const RinnovoScadenzeRoute = RinnovoScadenzeRouteImport.update({
  id: '/rinnovo-scadenze',
  path: '/rinnovo-scadenze',
  getParentRoute: () => rootRouteImport,
} as any)
const PostFreezeRoute = PostFreezeRouteImport.update({
  id: '/post-freeze',
  path: '/post-freeze',
  getParentRoute: () => rootRouteImport,
} as any)
const NuoviFabbisogniRoute = NuoviFabbisogniRouteImport.update({
  id: '/nuovi-fabbisogni',
  path: '/nuovi-fabbisogni',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitoraggioRoute = MonitoraggioRouteImport.update({
  id: '/monitoraggio',
  path: '/monitoraggio',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterplanSupcRoute = MasterplanSupcRouteImport.update({
  id: '/masterplan-supc',
  path: '/masterplan-supc',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterplanRuRoute = MasterplanRuRouteImport.update({
  id: '/masterplan-ru',
  path: '/masterplan-ru',
  getParentRoute: () => rootRouteImport,
} as any)
const MasterplanConsolidatoRoute = MasterplanConsolidatoRouteImport.update({
  id: '/masterplan-consolidato',
  path: '/masterplan-consolidato',
  getParentRoute: () => rootRouteImport,
} as any)
const ContrattiAttiviRoute = ContrattiAttiviRouteImport.update({
  id: '/contratti-attivi',
  path: '/contratti-attivi',
  getParentRoute: () => rootRouteImport,
} as any)
const CapacityRoute = CapacityRouteImport.update({
  id: '/capacity',
  path: '/capacity',
  getParentRoute: () => rootRouteImport,
} as any)
const AttivitaRoute = AttivitaRouteImport.update({
  id: '/attivita',
  path: '/attivita',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attivita': typeof AttivitaRoute
  '/capacity': typeof CapacityRoute
  '/contratti-attivi': typeof ContrattiAttiviRoute
  '/masterplan-consolidato': typeof MasterplanConsolidatoRoute
  '/masterplan-ru': typeof MasterplanRuRoute
  '/masterplan-supc': typeof MasterplanSupcRoute
  '/monitoraggio': typeof MonitoraggioRoute
  '/nuovi-fabbisogni': typeof NuoviFabbisogniRoute
  '/post-freeze': typeof PostFreezeRoute
  '/rinnovo-scadenze': typeof RinnovoScadenzeRoute
  '/savings': typeof SavingsRoute
  '/tempistiche': typeof TempisticheRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attivita': typeof AttivitaRoute
  '/capacity': typeof CapacityRoute
  '/contratti-attivi': typeof ContrattiAttiviRoute
  '/masterplan-consolidato': typeof MasterplanConsolidatoRoute
  '/masterplan-ru': typeof MasterplanRuRoute
  '/masterplan-supc': typeof MasterplanSupcRoute
  '/monitoraggio': typeof MonitoraggioRoute
  '/nuovi-fabbisogni': typeof NuoviFabbisogniRoute
  '/post-freeze': typeof PostFreezeRoute
  '/rinnovo-scadenze': typeof RinnovoScadenzeRoute
  '/savings': typeof SavingsRoute
  '/tempistiche': typeof TempisticheRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attivita': typeof AttivitaRoute
  '/capacity': typeof CapacityRoute
  '/contratti-attivi': typeof ContrattiAttiviRoute
  '/masterplan-consolidato': typeof MasterplanConsolidatoRoute
  '/masterplan-ru': typeof MasterplanRuRoute
  '/masterplan-supc': typeof MasterplanSupcRoute
  '/monitoraggio': typeof MonitoraggioRoute
  '/nuovi-fabbisogni': typeof NuoviFabbisogniRoute
  '/post-freeze': typeof PostFreezeRoute
  '/rinnovo-scadenze': typeof RinnovoScadenzeRoute
  '/savings': typeof SavingsRoute
  '/tempistiche': typeof TempisticheRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attivita'
    | '/capacity'
    | '/contratti-attivi'
    | '/masterplan-consolidato'
    | '/masterplan-ru'
    | '/masterplan-supc'
    | '/monitoraggio'
    | '/nuovi-fabbisogni'
    | '/post-freeze'
    | '/rinnovo-scadenze'
    | '/savings'
    | '/tempistiche'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attivita'
    | '/capacity'
    | '/contratti-attivi'
    | '/masterplan-consolidato'
    | '/masterplan-ru'
    | '/masterplan-supc'
    | '/monitoraggio'
    | '/nuovi-fabbisogni'
    | '/post-freeze'
    | '/rinnovo-scadenze'
    | '/savings'
    | '/tempistiche'
  id:
    | '__root__'
    | '/'
    | '/attivita'
    | '/capacity'
    | '/contratti-attivi'
    | '/masterplan-consolidato'
    | '/masterplan-ru'
    | '/masterplan-supc'
    | '/monitoraggio'
    | '/nuovi-fabbisogni'
    | '/post-freeze'
    | '/rinnovo-scadenze'
    | '/savings'
    | '/tempistiche'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttivitaRoute: typeof AttivitaRoute
  CapacityRoute: typeof CapacityRoute
  ContrattiAttiviRoute: typeof ContrattiAttiviRoute
  MasterplanConsolidatoRoute: typeof MasterplanConsolidatoRoute
  MasterplanRuRoute: typeof MasterplanRuRoute
  MasterplanSupcRoute: typeof MasterplanSupcRoute
  MonitoraggioRoute: typeof MonitoraggioRoute
  NuoviFabbisogniRoute: typeof NuoviFabbisogniRoute
  PostFreezeRoute: typeof PostFreezeRoute
  RinnovoScadenzeRoute: typeof RinnovoScadenzeRoute
  SavingsRoute: typeof SavingsRoute
  TempisticheRoute: typeof TempisticheRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tempistiche': {
      id: '/tempistiche'
      path: '/tempistiche'
      fullPath: '/tempistiche'
      preLoaderRoute: typeof TempisticheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/savings': {
      id: '/savings'
      path: '/savings'
      fullPath: '/savings'
      preLoaderRoute: typeof SavingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rinnovo-scadenze': {
      id: '/rinnovo-scadenze'
      path: '/rinnovo-scadenze'
      fullPath: '/rinnovo-scadenze'
      preLoaderRoute: typeof RinnovoScadenzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-freeze': {
      id: '/post-freeze'
      path: '/post-freeze'
      fullPath: '/post-freeze'
      preLoaderRoute: typeof PostFreezeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nuovi-fabbisogni': {
      id: '/nuovi-fabbisogni'
      path: '/nuovi-fabbisogni'
      fullPath: '/nuovi-fabbisogni'
      preLoaderRoute: typeof NuoviFabbisogniRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitoraggio': {
      id: '/monitoraggio'
      path: '/monitoraggio'
      fullPath: '/monitoraggio'
      preLoaderRoute: typeof MonitoraggioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masterplan-supc': {
      id: '/masterplan-supc'
      path: '/masterplan-supc'
      fullPath: '/masterplan-supc'
      preLoaderRoute: typeof MasterplanSupcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masterplan-ru': {
      id: '/masterplan-ru'
      path: '/masterplan-ru'
      fullPath: '/masterplan-ru'
      preLoaderRoute: typeof MasterplanRuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masterplan-consolidato': {
      id: '/masterplan-consolidato'
      path: '/masterplan-consolidato'
      fullPath: '/masterplan-consolidato'
      preLoaderRoute: typeof MasterplanConsolidatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contratti-attivi': {
      id: '/contratti-attivi'
      path: '/contratti-attivi'
      fullPath: '/contratti-attivi'
      preLoaderRoute: typeof ContrattiAttiviRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capacity': {
      id: '/capacity'
      path: '/capacity'
      fullPath: '/capacity'
      preLoaderRoute: typeof CapacityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attivita': {
      id: '/attivita'
      path: '/attivita'
      fullPath: '/attivita'
      preLoaderRoute: typeof AttivitaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttivitaRoute: AttivitaRoute,
  CapacityRoute: CapacityRoute,
  ContrattiAttiviRoute: ContrattiAttiviRoute,
  MasterplanConsolidatoRoute: MasterplanConsolidatoRoute,
  MasterplanRuRoute: MasterplanRuRoute,
  MasterplanSupcRoute: MasterplanSupcRoute,
  MonitoraggioRoute: MonitoraggioRoute,
  NuoviFabbisogniRoute: NuoviFabbisogniRoute,
  PostFreezeRoute: PostFreezeRoute,
  RinnovoScadenzeRoute: RinnovoScadenzeRoute,
  SavingsRoute: SavingsRoute,
  TempisticheRoute: TempisticheRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
